#!/usr/bin/env sh

node tools/check-verilog-tabs.js
status=$?

if [ $status -ne 0 ]; then
  exit $status
fi

node tools/bump-version.js
status=$?

if [ $status -ne 0 ]; then
  exit $status
fi

git add package.json

exit 0
